### ISSUE TITLE
Gentarium wants to hold masternode deposits for 7 days before withrawing

### ISSUE THREAD

**Issue by LibertyPimp** [genterium-project/gentarium#2]
There is no reason for Gentarium to hold MN deposits for 7 days before they withdraw the coins. It doesn't matter that they disclose this in some lengthy agreement, it goes against what the industry standard is, which is less than a day. They are, in fact, hijacking your coins for up to 6 days or more, there is no need for this and it is an abusive practice.

**Comment by genterium-project** [comment]
Are you really wanted to write this in the github core of the coin?
It's offtop.

**Comment by Treece57** [comment]
LibertyPimp is right! Genterium is nearly a scam... Ive had a terrible experience with them. There support is always there for you but only with lies and false info. Just learn how to run your own masternode and pay for the vps like i did - There is no reason to pay these fools. You will be raped in charges per masternode on their platform AND the withdraw time ? forever. Gentarium sucks case closed.
